INPUT:
  # PIXEL_MEAN: [17.58, 20.57, 21.54]
  PIXEL_MEAN: [17.58, 20.57, 21.54, 39.64, 41.40]
  PIXEL_STD: [1., 1., 1., 1., 1.]
  MIN_SIZE_TRAIN: (400,)
  MIN_SIZE_TEST: 400
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  VERTICAL_FLIP_PROB_TRAIN: 0.5
  ROTATE_PROB_TRAIN: 0.0
MODEL:
  IM_CHANNELS: 5
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  ROTATED: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    FREEZE_CONV_BODY_AT: -1
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    NMS_THRESH: 0.5
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.1
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    STRADDLE_THRESH: -1
    ANCHOR_ANGLES: (-90, -60, -30)
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0, 1.0)
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    FG_IOU_THRESHOLD: 0.3
    BG_IOU_THRESHOLD: 0.3
    NMS: 0.01
    SCORE_THRESH: 0.4
    USE_FPN: True
    DETECTIONS_PER_IMG: 10
    # weights on (dx, dy, dw, dh, dtheta) for normalizing rotated rect regression targets
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 1.0)
    USE_SOFT_NMS: True
    SOFT_NMS:
      METHOD: 1
  ROI_BOX_HEAD:
    NUM_CLASSES : 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  MASKIOU_ON: True
  ROI_MASKIOU_HEAD:
    USE_NMS: True
DATASETS:
  TRAIN: ("beaches_2k_train", "beaches_2k_val")
  TEST: ("beaches_2k_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, 105000)
  MAX_ITER: 100000
OUTPUT_DIR: "checkpoints/rotated/mscoco_msrcnn"
